version: '3'
services:
  rabbitmq:
    image: shoppingcart-rabbitmq
    build:
      context: src/docker
      dockerfile: rabbitmq-Dockerfile
    volumes:
      - rabbitmq_etc:/etc/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    network_mode: "host"
  gateway:
    build:
      context: src
      dockerfile: docker/api_gateway-Dockerfile
    image: shoppingcart-gateway
    depends_on:
      - rabbitmq
    ports:
      - "8888:8888"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  audit:
    build:
      context: src
      dockerfile: docker/audit_service-Dockerfile
    image: shoppingcart-audit
    ports:
      - "8806:8806"
    depends_on:
      - sqlexpress
    network_mode: "host"
  catalog:
    build:
      context: src
      dockerfile: docker/catalog_service-Dockerfile
    image: shoppingcart-catalog
    ports:
      - "8803:8803"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  checkout:
    build:
      context: src
      dockerfile: docker/checkout_service-Dockerfile
    image: shoppingcart-checkout
    ports:
      - "8804:8804"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  customer:
    build:
      context: src
      dockerfile: docker/customer_service-Dockerfile
    image: shoppingcart-customer
    ports:
      - "8801:8801"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  payment:
    build:
      context: src
      dockerfile: docker/payment_service-Dockerfile
    image: shoppingcart-payment
    depends_on:
      - rabbitmq
    ports:
      - "8805:8805"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  order:
    build:
      context: src
      dockerfile: docker/order_service-Dockerfile
    image: shoppingcart-order
    depends_on:
      - rabbitmq
    ports:
      - "8802:8802"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  security:
    build:
      context: src
      dockerfile: docker/security_service-Dockerfile
    image: shoppingcart-security
    depends_on:
      - gateway
    ports:
      - "9999:9999"
    depends_on:
      - sqlexpress
      - rabbitmq
    network_mode: "host"
  web:
    build:
      context: src
      dockerfile: docker/web-Dockerfile
    image: shoppingcart-web
    depends_on:
      - gateway
      - audit
      - catalog
      - customer
      - order
      - payment
      - security
    ports:
      - "3000:80"
    network_mode: "host"
  sqlexpress:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "123456"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    network_mode: "host"

volumes:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
  db_data:
